version: '3.9'
services:
  cat-api:
    image: luhanlacerda/cat-api:latest
    container_name: cat-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://cat-api-mssql:1433;databaseName=master
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=C@t-@p11234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - cron.expression=0 */1 * * * *
    ports:
      - "8080:8080"
    restart: on-failure
  cat-api-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: cat-api-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=C@t-@p11234
    ports:
      - "1433:1433"